/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scgproyectoradon1;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel E Guancha
 */
public class JframeEstadisticas extends javax.swing.JFrame {

    private String estacion;
    private String fechaDesde;
    private String fechaHasta;
    private DefaultTableModel model;
    
    private  Conexion conexion = new Conexion();
    private  JframeDatosRadon mainJframeRadon = new JframeDatosRadon();
    private  ArrayList<DatosEstadisticos> datosEstadisticos = new ArrayList<>();
    
    int año;
    int mes;
    int dia;
    
    /**
     * Constructor con parametros iniciales
     * @param jframeDatosRadon : recibe los parametros de la clase principal
     * @param tipo : indica el tipo de filtro que se va a realizar
     */
    public JframeEstadisticas(JframeDatosRadon jframeDatosRadon,String estacion,String fechaInicial, String fechaFinal) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.mainJframeRadon = jframeDatosRadon;
        this.estacion = estacion;
        this.fechaDesde = fechaInicial;
        this.fechaHasta = fechaFinal;
        
        lbl_estacion.setText("Estación: "+estacion);
        lbl_fecha.setText(fechaDesde + "  -  "+ fechaHasta);
        jdate_fecha_desde.setDate(new Date(fechaDesde.replace('-', '/')));
        
        jrbtn_rango.setSelected(false);
        
        if(jrbtn_rango.isSelected() == false){
            
            lbl_dia2.setEnabled(false);
            lbl_hasta.setEnabled(false);
            jdate_fecha_hasta.setEnabled(false);
        }
       
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdate_fechaDesde = new com.toedter.calendar.JDateChooser();
        lbl_estacion = new javax.swing.JLabel();
        lbl_subtitulo = new javax.swing.JLabel();
        lbl = new javax.swing.JLabel();
        btn_generar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        lbl_dia1 = new javax.swing.JLabel();
        lbl_fecha = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jrbtn_rango = new javax.swing.JRadioButton();
        lbl_dia2 = new javax.swing.JLabel();
        lbl_hasta = new javax.swing.JLabel();
        jdate_fecha_desde = new com.toedter.calendar.JDateChooser();
        jdate_fecha_hasta = new com.toedter.calendar.JDateChooser();

        jdate_fechaDesde.setDateFormatString("yyyy/MM/dd");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filtrar Datos");

        lbl_estacion.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lbl_estacion.setText("Estación:");

        lbl_subtitulo.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        lbl_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo.setText("Generar Estadisticas");

        lbl.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lbl.setText("Fecha de los datos:");

        btn_generar.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btn_generar.setText("Generar");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        btn_cancelar.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        btn_cancelar.setText("Cancelar");

        lbl_dia1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lbl_dia1.setText("Día:");

        lbl_fecha.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lbl_fecha.setForeground(new java.awt.Color(0, 204, 0));
        lbl_fecha.setText("yyyy/mm/dd");

        lbl1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lbl1.setText("Generar estadisticas por:");

        jrbtn_rango.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jrbtn_rango.setText("Rango de días");
        jrbtn_rango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtn_rangoActionPerformed(evt);
            }
        });

        lbl_dia2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lbl_dia2.setText("Día:");

        lbl_hasta.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        lbl_hasta.setText("Hasta");

        jdate_fecha_desde.setDateFormatString("yyyy/MM/dd");
        jdate_fecha_desde.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jdate_fecha_hasta.setDateFormatString("yyyy/MM/dd");
        jdate_fecha_hasta.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_subtitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jdate_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_dia2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdate_fecha_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbtn_rango)
                            .addComponent(lbl_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_subtitulo)
                .addGap(18, 18, 18)
                .addComponent(lbl_estacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbtn_rango)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_fecha_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jdate_fecha_hasta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_dia1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dia2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
     
        model = new DefaultTableModel(new Object[]{"Periodo Calculado","Minimo","Maximo","Rango","Promedio"},0);
        mainJframeRadon.jtablaEstadisticas.setModel(model);
        mainJframeRadon.jtablaEstadisticas.setFont(new Font("Open Sans",Font.PLAIN,14));
        
        año = jdate_fecha_desde.getCalendar().get(Calendar.YEAR);
        mes = jdate_fecha_desde.getCalendar().get(Calendar.MONTH)+1;
        dia = jdate_fecha_desde.getCalendar().get(Calendar.DAY_OF_MONTH);

        fechaDesde = año + "/" + mes + "/" + dia;
        
       
        
        if(jrbtn_rango.isSelected() == false){
            Estadisticas estadisticas = new Estadisticas(estacion, fechaDesde, fechaDesde);
            datosEstadisticos.add(new DatosEstadisticos(fechaDesde, estadisticas.getMinimo(),estadisticas.getMaximo(), estadisticas.getRango(), estadisticas.getPromedio()));
           
        }else
        {
            año = jdate_fecha_hasta.getCalendar().get(Calendar.YEAR);
            mes = jdate_fecha_hasta.getCalendar().get(Calendar.MONTH)+1;
            dia = jdate_fecha_hasta.getCalendar().get(Calendar.DAY_OF_MONTH);
            
            fechaHasta = año + "/" + mes + "/" + dia;
            
            Estadisticas estadisticas = new Estadisticas(estacion, fechaDesde, fechaHasta);
            datosEstadisticos.add(new DatosEstadisticos(fechaDesde + " - " + fechaHasta , estadisticas.getMinimo(),estadisticas.getMaximo(), estadisticas.getRango(), estadisticas.getPromedio()));
        }
        
        for (DatosEstadisticos datoE : datosEstadisticos) {
            
            model.addRow(new Object[]{datoE.getFecha(),datoE.getMinimo(),datoE.getMaximo(),datoE.getRango(),datoE.getPromedio()});
            
        }
    }//GEN-LAST:event_btn_generarActionPerformed

    private void jrbtn_rangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtn_rangoActionPerformed
       if(jrbtn_rango.isSelected() == false){
            
            lbl_dia2.setEnabled(false);
            lbl_hasta.setEnabled(false);
            jdate_fecha_hasta.setEnabled(false);
        }else{
           lbl_dia2.setEnabled(true);
           lbl_hasta.setEnabled(true);
           jdate_fecha_hasta.setEnabled(true);
           jdate_fecha_hasta.setDate(new Date(fechaHasta.replace('-', '/')));
           
       }
    }//GEN-LAST:event_jrbtn_rangoActionPerformed

    /**
     * Metodo para validar las entradas de los campos 
     * @return : retorna verdadero si los campos son correctos, 
     * de lo contario retornara falso
     */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_generar;
    protected com.toedter.calendar.JDateChooser jdate_fechaDesde;
    protected com.toedter.calendar.JDateChooser jdate_fecha_desde;
    protected com.toedter.calendar.JDateChooser jdate_fecha_hasta;
    private javax.swing.JRadioButton jrbtn_rango;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl_dia1;
    private javax.swing.JLabel lbl_dia2;
    private javax.swing.JLabel lbl_estacion;
    private javax.swing.JLabel lbl_fecha;
    private javax.swing.JLabel lbl_hasta;
    private javax.swing.JLabel lbl_subtitulo;
    // End of variables declaration//GEN-END:variables
}
