/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scgproyectoradon1;

import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel E Guancha
 */
public class JframeFiltrar extends javax.swing.JFrame {

    private String estacion;
    private String fechaDesde;
    private String fechaHasta;
    
    private  Conexion conexion = new Conexion();
    private JframeDatosRadon mainJframeRadon = new JframeDatosRadon();
    
    /**
     * Constructor con parametros iniciales
     * @param jframeDatosRadon : recibe los parametros de la clase principal
     * @param tipo : indica el tipo de filtro que se va a realizar
     */
    public JframeFiltrar(JframeDatosRadon jframeDatosRadon) {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.mainJframeRadon = jframeDatosRadon;
        
        
        for (Object estacion : conexion.getEstaciones()) {
            jcmb_estaciones.addItem(estacion.toString());
        }
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jcmb_estaciones = new javax.swing.JComboBox<>();
        lbl_subtitulo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jdate_fechaDesde = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jdate_fechaHasta = new com.toedter.calendar.JDateChooser();
        btn_aceptar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Filtrar Datos");

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Estación:");

        jcmb_estaciones.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jcmb_estaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione--" }));
        jcmb_estaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_estacionesActionPerformed(evt);
            }
        });

        lbl_subtitulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lbl_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_subtitulo.setText("Filtrar Datos por:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Fecha Desde:");

        jdate_fechaDesde.setDateFormatString("yyyy/MM/dd");

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Fecha Hasta:");

        jdate_fechaHasta.setDateFormatString("yyyy/MM/dd");

        btn_aceptar.setText("Aceptar");
        btn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarActionPerformed(evt);
            }
        });

        btn_cancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_subtitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdate_fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmb_estaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdate_fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_subtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcmb_estaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdate_fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdate_fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarActionPerformed
        if(ValidarEntradasFiltroBusqueda()){
            mainJframeRadon.datos.setEstacion(estacion);
            mainJframeRadon.datos.setFechaDesde(fechaDesde);
            mainJframeRadon.datos.setFechaHasta(fechaHasta);
            
           mainJframeRadon.buscarDatos();
           this.dispose();
            
        }
    }//GEN-LAST:event_btn_aceptarActionPerformed

    private void jcmb_estacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_estacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_estacionesActionPerformed

    /**
     * Metodo para validar las entradas de los campos 
     * @return : retorna verdadero si los campos son correctos, 
     * de lo contario retornara falso
     */
        private boolean ValidarEntradasFiltroBusqueda(){
        if(jcmb_estaciones.getSelectedIndex() > 0)
        {
            estacion = jcmb_estaciones.getSelectedItem().toString();
            System.out.println(estacion);

            // validar si el suario selecciono una fecha
            if(jdate_fechaDesde.getDate() != null){
                // filtro 2: fecha 
                // obtener la fecha

                int año = jdate_fechaDesde.getCalendar().get(Calendar.YEAR);
                int mes = jdate_fechaDesde.getCalendar().get(Calendar.MONTH)+1;
                int dia = jdate_fechaDesde.getCalendar().get(Calendar.DAY_OF_MONTH);

                fechaDesde = año + "/" + mes + "/" + dia;
                
                // validar si la fecha Inicial esta en la base de datos
                if(conexion.validarFecha(fechaDesde)){
                     // calcular fecha final con la suma de los dias

                   

                    año = jdate_fechaHasta.getCalendar().get(Calendar.YEAR);
                    mes = jdate_fechaHasta.getCalendar().get(Calendar.MONTH)+1;
                    dia = jdate_fechaHasta.getCalendar().get(Calendar.DAY_OF_MONTH);


                    fechaHasta = año + "/" + mes + "/" + dia;

                    // validar si la fecha final esta en la base de datos
                    if(conexion.validarFecha(fechaHasta)){
                        
                        return true;

                    }else{
                        JOptionPane.showMessageDialog(null, "No existe el rango de días selecionados");
                        return false;
                   
                    }

                }else{
                    JOptionPane.showMessageDialog(null, "La fecha inicial ingresada no es valida");
                    return false;  
                }

            }else
            {
               JOptionPane.showMessageDialog(null, "Debe seleccionar una fecha");
               return false;
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una estación");
            return false;  
        }
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    protected javax.swing.JComboBox<String> jcmb_estaciones;
    protected com.toedter.calendar.JDateChooser jdate_fechaDesde;
    protected com.toedter.calendar.JDateChooser jdate_fechaHasta;
    private javax.swing.JLabel lbl_subtitulo;
    // End of variables declaration//GEN-END:variables
}
