/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scgproyectoradon1;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/**
 *
 * @author Daniel E Guancha
 */
public class JframeDatosRadon extends javax.swing.JFrame {

    /**
     *
     */
    
    
    private  Conexion conexion = new Conexion();
    private  CalcularDatosAtipicos calcularDatosAtipicos = new CalcularDatosAtipicos();
    protected  Datos datos = new Datos();
    

    private JFileChooser guardar;
    private FileNameExtensionFilter filtro;

   
    // modelos
    
    DefaultTableModel model;
    /** 
     *Constructor por defecto
     **/
    
    public JframeDatosRadon() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        
        
        // deshabilitar botones
        
        activarBotones(false);
      
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabla_datos = new javax.swing.JTable();
        lbl_subtitulo = new javax.swing.JLabel();
        lbl_titulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtablaEstadisticas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_mediaMovil = new javax.swing.JButton();
        btn_exportar = new javax.swing.JButton();
        btn_descartar = new javax.swing.JButton();
        btn_estadisticas = new javax.swing.JButton();
        jpanel_Grafica = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMinimumSize(new java.awt.Dimension(1225, 279));

        jtabla_datos.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtabla_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Cod Estación", "Fecha", "Hora", "Concentración"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtabla_datos.setRowHeight(25);
        jScrollPane1.setViewportView(jtabla_datos);
        if (jtabla_datos.getColumnModel().getColumnCount() > 0) {
            jtabla_datos.getColumnModel().getColumn(0).setResizable(false);
            jtabla_datos.getColumnModel().getColumn(1).setResizable(false);
            jtabla_datos.getColumnModel().getColumn(2).setResizable(false);
            jtabla_datos.getColumnModel().getColumn(3).setResizable(false);
            jtabla_datos.getColumnModel().getColumn(4).setResizable(false);
        }

        lbl_subtitulo.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lbl_subtitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_subtitulo.setText("Estadisticas");

        lbl_titulo.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Tabla Datos");

        jScrollPane2.setHorizontalScrollBar(null);
        jScrollPane2.setMinimumSize(new java.awt.Dimension(100, 100));

        jtablaEstadisticas.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jtablaEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Minimo", "Maximo", "Rango", "Promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtablaEstadisticas.setRowHeight(25);
        jScrollPane2.setViewportView(jtablaEstadisticas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_subtitulo)
                .addGap(548, 548, 548))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_subtitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_buscar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_mediaMovil.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_mediaMovil.setText("Media Movil");
        btn_mediaMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mediaMovilActionPerformed(evt);
            }
        });

        btn_exportar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_exportar.setText("Exportar");
        btn_exportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportarActionPerformed(evt);
            }
        });

        btn_descartar.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_descartar.setText("Descartar Atipicos");
        btn_descartar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descartarActionPerformed(evt);
            }
        });

        btn_estadisticas.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        btn_estadisticas.setText("Estadisticas");
        btn_estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estadisticasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_descartar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mediaMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_descartar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_mediaMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_exportar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        jpanel_Grafica.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpanel_Grafica.setAutoscrolls(true);

        javax.swing.GroupLayout jpanel_GraficaLayout = new javax.swing.GroupLayout(jpanel_Grafica);
        jpanel_Grafica.setLayout(jpanel_GraficaLayout);
        jpanel_GraficaLayout.setHorizontalGroup(
            jpanel_GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpanel_GraficaLayout.setVerticalGroup(
            jpanel_GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpanel_Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1215, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jpanel_Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abre una ventana de dialogo, para recibir los parametro de busqueda
     **/
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        
        JframeFiltrar jframeFiltrar = new JframeFiltrar(this);
        jframeFiltrar.setVisible(true);
        jframeFiltrar.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_btn_buscarActionPerformed

     /**
     * Abre una ventana de confirmación de eliminación de un elemento
     * seleccionado en la tabla, de acuerdo al resultado de la confirmación de eliminación
     * se elimina o se conserva el registro seleccionado
     **/
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        
   
        double datoAtipico = Double.parseDouble(jtabla_datos.getValueAt(jtabla_datos.getSelectedRow(), 4).toString());
        int opcionEliminar = JOptionPane.showConfirmDialog(null, "Desea Eliminar el dato seleccionado?\n\n Dato: "+datoAtipico ,"Eliminar Dato Atipico",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);

        if(opcionEliminar == 0){
            conexion.eliminarDatosAtipicos(datos.getCodestacion(), datos.getFechaDesde(), datos.getFechaHasta()
                    , datoAtipico);
            model.removeRow(jtabla_datos.getSelectedRow());

            jtabla_datos.updateUI();

        }       
        
    }//GEN-LAST:event_btn_eliminarActionPerformed

     /**
     * Abre una ventana, el cual recibe los parametros con los cuales se 
     * calculara la media movil
     **/
    private void btn_mediaMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mediaMovilActionPerformed
        JframeMediaMovil jframeMediaMovil = new JframeMediaMovil(this);
        jframeMediaMovil.setVisible(true);
        jframeMediaMovil.setDefaultCloseOperation(DISPOSE_ON_CLOSE);     
    }//GEN-LAST:event_btn_mediaMovilActionPerformed

    /**
     * Abre una ventana de dialogo, en la cual se selecciona la ubicación 
     * donde se exportara el archivo Excel con los datos de la tabla 
     **/
    private void btn_exportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportarActionPerformed
    ExportarExcel exportarExcel = new ExportarExcel();

        guardar = new JFileChooser();
        
        guardar.setAcceptAllFileFilterUsed(false);
        
        filtro = new FileNameExtensionFilter("Excel .xlsx",".xlsx");
        guardar.setFileFilter(filtro);

        
        int seleccion = guardar.showSaveDialog(this);
        
        
        if(seleccion == JFileChooser.APPROVE_OPTION){
            
            exportarExcel.exportar(jtabla_datos,guardar.getSelectedFile() , "Datos "+datos.getEstacion()+" "+datos.getFechaDesde().replace('/', '-'),guardar.getFileFilter());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exportarActionPerformed

     /**
     * Acción para descartar los datos atipicos encontrados
     **/
    private void btn_descartarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descartarActionPerformed
        
        datos.datosRadon.clear();
        System.out.println("tamaño quedo " + datos.datosRadon.size());
        datos.datosRadon.addAll(conexion.getDatos(datos.getEstacion(), datos.getFechaDesde(), datos.getFechaHasta()));
        cargarDatos(datos.datosRadon, false, false);
       
    }//GEN-LAST:event_btn_descartarActionPerformed

     /**
     * Evento btn_estadisticasActionPerformed
     * Abre una ventana de dialogo en el cual se especifica los parametros
     * para generar las estadisticas
     **/
    private void btn_estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estadisticasActionPerformed
        JframeEstadisticas jframeEstadisticas= new JframeEstadisticas(this, datos.getEstacion(), datos.getFechaDesde(), datos.getFechaHasta());
        jframeEstadisticas.setVisible(true);
        jframeEstadisticas.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btn_estadisticasActionPerformed

    /**
     * Metodo por defecto
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeDatosRadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeDatosRadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeDatosRadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeDatosRadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(JframeDatosRadon.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(JframeDatosRadon.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(JframeDatosRadon.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(JframeDatosRadon.class.getName()).log(Level.SEVERE, null, ex);
                }
                new JframeDatosRadon().setVisible(true);
            }
        });
    }
    
    /**
     * Invoca a la clase Conexion para realizar la busqueda de datos 
     * y los almacena en la clase Datos
     **/
    public void buscarDatos(){
        
    // obtener los datos deacuerdo a los filtros dados

        datos.setDatosRadon(conexion.getDatos(datos.getEstacion(), datos.getFechaDesde(), datos.getFechaHasta()))  ;
        if(!datos.getDatosRadon().isEmpty()){
            //envio los datos capturados a verificar si existen datos atipicos
            ArrayList<Double> datosAtipicos = new ArrayList<>();


            datosAtipicos = calcularDatosAtipicos.Calcular_Datos_Atipicos(datos.getDatosRadon());

            // buscamos datos atipicos si existen

            if(!datosAtipicos.isEmpty()){
                JOptionPane.showMessageDialog(null, "Se encontraron algunos posibles Datos Atipicos");
                
                cargarDatos(conexion.getDatosAtipicos(datosAtipicos,datos.getEstacion(), datos.getFechaDesde(), datos.getFechaHasta()),true,false);

            }else{
                JOptionPane.showMessageDialog(null, "No se encontraron datos atipicos en\n\n"
                                            + "Estación: " +datos.getEstacion() +"\n"
                                            + "Fecha inicio: "+datos.getFechaDesde()+"\n"
                                            + "Fecha Fin: "+datos.getFechaHasta());

                cargarDatos(datos.getDatosRadon(),false,false);

            }
        
         graficar();
        
        }else{
            JOptionPane.showMessageDialog(null, "No se encontraron Datos \n"
                                                + "En el rango de fechas ingresadas");
            activarBotones(false);
            
        }  
    }

    
    /**

     * Carga la infomación en la tabla principal recibiendo los siguientes parametros:
     * 
     * @param datos : ArrayList de tipo Datos contiene los datos obtenidos de las consultas a la base de datos
     * @param existeAtipico : Variable de tipo Boolean que indica si los datos que ingresan son datos atipicos
     * @param mediaMovil : Variable de tipo Boolean que indica si los datos que ingresan contiene media movil
     * 
     **/
    protected void cargarDatos(ArrayList<Datos> datos,boolean existeAtipico,boolean mediaMovil) {
        if(mediaMovil)model = new DefaultTableModel(new Object[]{"#","Estación","Fecha","Hora","Concentración","Media Movil"},0);
        else model = new DefaultTableModel(new Object[]{"#","Estación","Fecha","Hora","Concentración"},0);
        
        
        if (existeAtipico){
            lbl_titulo.setText("Tabla datos Atipicos :   "+ this.datos.getEstacion()+"   "+this.datos.getFechaDesde()+"  --  "+this.datos.getFechaHasta());
            
            btn_mediaMovil.setEnabled(false);
            btn_eliminar.setEnabled(true);
            btn_descartar.setEnabled(true);
            btn_exportar.setEnabled(true);
            btn_estadisticas.setEnabled(true);
            
            jtabla_datos.removeAll();
            jtabla_datos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jtabla_datos.setSelectionForeground(Color.RED);
            jtabla_datos.setSelectionBackground(Color.BLACK);
        }
        else {
            lbl_titulo.setText("Tabla datos :   "+ this.datos.getEstacion()+"   "+this.datos.getFechaDesde()+"  --  "+this.datos.getFechaHasta()); 
            
            btn_mediaMovil.setEnabled(true);
            btn_eliminar.setEnabled(false);
            btn_descartar.setEnabled(false);
            btn_exportar.setEnabled(true);
            btn_estadisticas.setEnabled(true);
            
            jtabla_datos.removeAll();
            jtabla_datos.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
            jtabla_datos.setSelectionForeground(Color.blue);
            jtabla_datos.setSelectionBackground(Color.GREEN);
            
            
        }
        
        jtabla_datos.setModel(model);
    
       if(mediaMovil){
            for (Datos dato : datos) {
                model.addRow(new Object[]{jtabla_datos.getRowCount()+1,dato.getCodestacion(),dato.getFecha(),dato.getHora(),dato.getConcentracion(),dato.getPromediomovil()});
            }
       }else{
            for (Datos dato : datos) {
            model.addRow(new Object[]{jtabla_datos.getRowCount()+1,dato.getCodestacion(),dato.getFecha(),dato.getHora(),dato.getConcentracion()});
            }
       }
    }
    

    
    /**
  
     * @param activar : Variable de tipo Boolean activa o desactiva los botones de la interfaz principal
     * cuando se requien
     */
    
    private void activarBotones(boolean activar){
        btn_mediaMovil.setEnabled(activar);
        btn_eliminar.setEnabled(activar);
        btn_descartar.setEnabled(activar);
        btn_exportar.setEnabled(activar);
        btn_estadisticas.setEnabled(activar);
    }
    
    /**
     * 
     */
    
    protected void graficar(){
        
       
        
        JFreeChart grafica_dispersion = ChartFactory.createScatterPlot(
                "grafico dispersion",
                "tiempo",
                "concentracion",
                dataSet(),
                PlotOrientation.VERTICAL,
                true,
                true,
                false);
        
        ChartPanel panelG = new ChartPanel(grafica_dispersion);
        panelG.setDomainZoomable(true);
        panelG.setVisible(true);
        
        jpanel_Grafica.setLayout(new BorderLayout());
        jpanel_Grafica.add(panelG,BorderLayout.CENTER);
        jpanel_Grafica.updateUI();
        
        
    }
    private XYDataset dataSet() {
        
        final XYSeries XYConcentracion = new XYSeries("Concentración");

        int i=0;
        
        
        for (Datos datos : datos.getDatosRadon()) {
            XYConcentracion.add(i++, datos.getConcentracion());
            
            
        }
          
        final XYSeriesCollection dataSet = new XYSeriesCollection();
           
         dataSet.addSeries(XYConcentracion);
     
        
       
        
        return dataSet;
    }

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_descartar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_estadisticas;
    private javax.swing.JButton btn_exportar;
    private javax.swing.JButton btn_mediaMovil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpanel_Grafica;
    protected javax.swing.JTable jtablaEstadisticas;
    protected javax.swing.JTable jtabla_datos;
    private javax.swing.JLabel lbl_subtitulo;
    protected javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables

    
}
